-- V1: schema ตั้งต้น (ตรงกับฐานข้อมูลก่อนเริ่มใช้ Flyway) ถูกสร้างจาก pg_dump --schema-only
CREATE TABLE activities (
    activity_time timestamp(6) without time zone,
    id bigint NOT NULL,
    trip_id bigint,
    location character varying(150),
    title character varying(255),
    activity_date date,
    category character varying(20),
    created_at timestamp(6) without time zone,
    created_by_member_id bigint,
    end_time time(0) without time zone,
    notes character varying(500),
    start_time time(0) without time zone,
    booked boolean,
    booking_method character varying(20),
    booking_ref character varying(100),
    contact character varying(100),
    cost numeric(10,2),
    end_date date,
    guests_per_room integer,
    latitude double precision,
    longitude double precision,
    meal_type character varying(20),
    origin character varying(150),
    rooms integer,
    transport_mode character varying(20),
    poll_id bigint,
    cost_currency character varying(3),
    cost_rate numeric(14,6)
);
ALTER TABLE activities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME activities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE activity_participants (
    activity_id bigint NOT NULL,
    member_id bigint,
    "position" integer NOT NULL,
    CONSTRAINT activity_participants_position_check CHECK (("position" >= 0))
);
CREATE TABLE activity_stops (
    activity_id bigint NOT NULL,
    arrive_time time(0) without time zone,
    depart_time time(0) without time zone,
    place character varying(150),
    "position" integer NOT NULL,
    CONSTRAINT activity_stops_position_check CHECK (("position" >= 0))
);
CREATE TABLE checklist_item_assignees (
    item_id bigint NOT NULL,
    member_id bigint,
    "position" integer NOT NULL,
    CONSTRAINT checklist_item_assignees_position_check CHECK (("position" >= 0))
);
CREATE TABLE checklist_items (
    is_checked boolean,
    assigned_to_member_id bigint,
    id bigint NOT NULL,
    trip_id bigint,
    updated_by_member_id bigint,
    category character varying(255),
    item_name character varying(255),
    notes character varying(255),
    quantity numeric(10,2),
    unit character varying(255)
);
ALTER TABLE checklist_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME checklist_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE expense_splits (
    amount_owed numeric(38,2),
    percentage numeric(38,2),
    expense_id bigint,
    id bigint NOT NULL,
    trip_member_id bigint,
    is_paid boolean DEFAULT false NOT NULL,
    paid_amount numeric(10,2)
);
ALTER TABLE expense_splits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME expense_splits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE expenses (
    total_amount numeric(38,2),
    expense_date timestamp(6) without time zone,
    id bigint NOT NULL,
    trip_id bigint,
    user_id bigint,
    category character varying(255),
    currency character varying(255),
    split_type character varying(255),
    title character varying(255),
    activity_id bigint,
    exchange_rate numeric(14,6),
    original_amount numeric(12,2),
    recorded_by_member_id bigint,
    revision integer
);
ALTER TABLE expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME expenses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE poll_options (
    id bigint NOT NULL,
    poll_id bigint,
    option_text character varying(255)
);
ALTER TABLE poll_options ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME poll_options_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE poll_votes (
    id bigint NOT NULL,
    member_id bigint,
    option_id bigint,
    poll_id bigint
);
ALTER TABLE poll_votes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME poll_votes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE polls (
    id bigint NOT NULL,
    trip_id bigint,
    question character varying(255),
    status character varying(255),
    created_at timestamp(6) without time zone,
    created_by_member_id bigint,
    closes_at timestamp(6) without time zone
);
ALTER TABLE polls ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME polls_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE repayment_items (
    repayment_id bigint NOT NULL,
    amount numeric(10,2),
    expense_id bigint,
    split_id bigint,
    title character varying(150),
    "position" integer NOT NULL,
    CONSTRAINT repayment_items_position_check CHECK (("position" >= 0))
);
CREATE TABLE repayments (
    id bigint NOT NULL,
    amount numeric(10,2),
    created_at timestamp(6) without time zone,
    from_member_id bigint,
    to_member_id bigint,
    trip_id bigint
);
ALTER TABLE repayments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME repayments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE trip_members (
    id bigint NOT NULL,
    joined_at timestamp(6) without time zone,
    trip_id bigint NOT NULL,
    guest_name character varying(255) NOT NULL,
    role character varying(255) NOT NULL
);
ALTER TABLE trip_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME trip_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE trips (
    end_date date,
    start_date date,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    invite_code character varying(255),
    title character varying(255),
    time_zone character varying(50),
    budget_per_person numeric(10,2),
    currency character varying(3),
    exchange_rate numeric(14,6)
);
ALTER TABLE trips ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME trips_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE user_trip_history (
    id bigint NOT NULL,
    trip_id bigint NOT NULL,
    user_id bigint NOT NULL,
    viewed_at timestamp(6) without time zone
);
ALTER TABLE user_trip_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_trip_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE users (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    username character varying(255) NOT NULL,
    auth_token character varying(64),
    pin_hash character varying(120),
    recovery_expires_at timestamp(6) without time zone,
    recovery_hash character varying(120)
);
ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY activities
    ADD CONSTRAINT activities_pkey PRIMARY KEY (id);
ALTER TABLE ONLY activity_participants
    ADD CONSTRAINT activity_participants_pkey PRIMARY KEY (activity_id, "position");
ALTER TABLE ONLY activity_stops
    ADD CONSTRAINT activity_stops_pkey PRIMARY KEY (activity_id, "position");
ALTER TABLE ONLY checklist_item_assignees
    ADD CONSTRAINT checklist_item_assignees_pkey PRIMARY KEY (item_id, "position");
ALTER TABLE ONLY checklist_items
    ADD CONSTRAINT checklist_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY expense_splits
    ADD CONSTRAINT expense_splits_pkey PRIMARY KEY (id);
ALTER TABLE ONLY expenses
    ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);
ALTER TABLE ONLY poll_options
    ADD CONSTRAINT poll_options_pkey PRIMARY KEY (id);
ALTER TABLE ONLY poll_votes
    ADD CONSTRAINT poll_votes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY poll_votes
    ADD CONSTRAINT poll_votes_poll_id_member_id_key UNIQUE (poll_id, member_id);
ALTER TABLE ONLY polls
    ADD CONSTRAINT polls_pkey PRIMARY KEY (id);
ALTER TABLE ONLY repayment_items
    ADD CONSTRAINT repayment_items_pkey PRIMARY KEY (repayment_id, "position");
ALTER TABLE ONLY repayments
    ADD CONSTRAINT repayments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY trip_members
    ADD CONSTRAINT trip_members_pkey PRIMARY KEY (id);
ALTER TABLE ONLY trips
    ADD CONSTRAINT trips_pkey PRIMARY KEY (id);
ALTER TABLE ONLY poll_votes
    ADD CONSTRAINT uk5aui3ahbiud7lch9cr4blftis UNIQUE (poll_id, member_id);
ALTER TABLE ONLY trip_members
    ADD CONSTRAINT uk_trip_members_trip_guest UNIQUE (trip_id, guest_name);
ALTER TABLE ONLY users
    ADD CONSTRAINT uk_users_username UNIQUE (username);
ALTER TABLE ONLY users
    ADD CONSTRAINT uklp8q49ht11h59aos3prhrjquo UNIQUE (auth_token);
ALTER TABLE ONLY user_trip_history
    ADD CONSTRAINT user_trip_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY checklist_item_assignees
    ADD CONSTRAINT fk1m9tx11rmmuig8obv40jtwsd1 FOREIGN KEY (item_id) REFERENCES checklist_items(id);
ALTER TABLE ONLY activity_participants
    ADD CONSTRAINT fk4jh3y144aog87xobqjb3yaca9 FOREIGN KEY (activity_id) REFERENCES activities(id);
ALTER TABLE ONLY expenses
    ADD CONSTRAINT fk9twvm79qw1voae3xgtn1xq5y9 FOREIGN KEY (trip_id) REFERENCES trips(id);
ALTER TABLE ONLY expense_splits
    ADD CONSTRAINT fkb47ab8horxyb1sbjir2q8iusx FOREIGN KEY (trip_member_id) REFERENCES trip_members(id);
ALTER TABLE ONLY repayment_items
    ADD CONSTRAINT fkb9mvh6obsm4c9la3qs8hr02mt FOREIGN KEY (repayment_id) REFERENCES repayments(id);
ALTER TABLE ONLY activity_stops
    ADD CONSTRAINT fkcds8k1ykv06268ewxu9li5tf3 FOREIGN KEY (activity_id) REFERENCES activities(id);
ALTER TABLE ONLY expenses
    ADD CONSTRAINT fkhw239eb88rqfdt5eoigqhdqsl FOREIGN KEY (user_id) REFERENCES trip_members(id);
ALTER TABLE ONLY activities
    ADD CONSTRAINT fkkx78ofjocchsrmnsf02creh65 FOREIGN KEY (trip_id) REFERENCES trips(id);
ALTER TABLE ONLY trip_members
    ADD CONSTRAINT fklrwxwvuaj3iddljvck3c3gtqr FOREIGN KEY (trip_id) REFERENCES trips(id);
ALTER TABLE ONLY expense_splits
    ADD CONSTRAINT fkqigr3qe91wgifpl6mak0xcdso FOREIGN KEY (expense_id) REFERENCES expenses(id);
