-- V2: One-to-One (trip_settings), Many-to-Many (ตารางกลางผูกกับ trip_members จริง), Index

-- ---------- 1) trips -> trip_settings (One-to-One) ----------
CREATE TABLE trip_settings (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id           BIGINT        NOT NULL,
    time_zone         VARCHAR(50),
    budget_per_person NUMERIC(10, 2),
    currency          VARCHAR(3),
    exchange_rate     NUMERIC(14, 6),
    -- UNIQUE ทำให้ 1 ทริปมีได้ชุดเดียว (หัวใจของ One-to-One), ลบทริปแล้วลบตั้งค่าตาม
    CONSTRAINT uk_trip_settings_trip UNIQUE (trip_id),
    CONSTRAINT fk_trip_settings_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE
);

-- ย้ายค่าเดิมของทุกทริป (ทริปที่ไม่เคยตั้งอะไรก็ได้แถวว่างหนึ่งแถว เพื่อให้ทุกทริปมี settings)
INSERT INTO trip_settings (trip_id, time_zone, budget_per_person, currency, exchange_rate)
SELECT id, time_zone, budget_per_person, currency, exchange_rate
FROM trips;

ALTER TABLE trips
    DROP COLUMN time_zone,
    DROP COLUMN budget_per_person,
    DROP COLUMN currency,
    DROP COLUMN exchange_rate;

-- ---------- 2) Many-to-Many: ผู้ร่วมกิจกรรม / ผู้รับผิดชอบเช็กลิสต์ ----------
-- ข้อมูลเก่าที่มีแค่ assigned_to_member_id ให้เป็นแถวในตารางกลางด้วย
INSERT INTO checklist_item_assignees (item_id, member_id, position)
SELECT ci.id, ci.assigned_to_member_id, 0
FROM checklist_items ci
WHERE ci.assigned_to_member_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM checklist_item_assignees a WHERE a.item_id = ci.id);

-- แถวที่ชี้ไปหาสมาชิกที่ไม่มีแล้ว ลบทิ้งก่อนใส่ FK
DELETE FROM activity_participants WHERE member_id IS NOT NULL AND member_id NOT IN (SELECT id FROM trip_members);
DELETE FROM checklist_item_assignees WHERE member_id IS NOT NULL AND member_id NOT IN (SELECT id FROM trip_members);

-- สมาชิกถูกลบ (ออกจากทริป) แล้วแถวในตารางกลางต้องหายตาม
ALTER TABLE activity_participants
    ADD CONSTRAINT fk_activity_participants_member FOREIGN KEY (member_id) REFERENCES trip_members (id) ON DELETE CASCADE;
ALTER TABLE checklist_item_assignees
    ADD CONSTRAINT fk_checklist_assignees_member FOREIGN KEY (member_id) REFERENCES trip_members (id) ON DELETE CASCADE;

-- checklist_items.trip_id เดิมเป็นแค่ตัวเลข ไม่มี FK
DELETE FROM checklist_items WHERE trip_id IS NOT NULL AND trip_id NOT IN (SELECT id FROM trips);
ALTER TABLE checklist_items
    ADD CONSTRAINT fk_checklist_items_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE;

-- ---------- 3) Index (ทุกตัวตรงกับ query ที่ใช้จริง: ดึงข้อมูลของทริปหนึ่ง / ของบิลหนึ่ง / ของคนหนึ่ง) ----------
CREATE INDEX IF NOT EXISTS idx_trips_invite_code ON trips (invite_code);               -- เข้าทริปด้วยรหัสเชิญ
CREATE INDEX IF NOT EXISTS idx_trip_members_trip ON trip_members (trip_id);            -- รายชื่อสมาชิกของทริป
CREATE INDEX IF NOT EXISTS idx_activities_trip ON activities (trip_id);                -- แพลนของทริป
CREATE INDEX IF NOT EXISTS idx_checklist_items_trip ON checklist_items (trip_id);      -- เช็กลิสต์ของทริป
CREATE INDEX IF NOT EXISTS idx_expenses_trip ON expenses (trip_id);                    -- บิลของทริป
CREATE INDEX IF NOT EXISTS idx_expense_splits_expense ON expense_splits (expense_id);  -- ส่วนแบ่งของบิล
CREATE INDEX IF NOT EXISTS idx_expense_splits_member ON expense_splits (trip_member_id); -- หนี้ของสมาชิก
CREATE INDEX IF NOT EXISTS idx_polls_trip ON polls (trip_id);                          -- โหวตของทริป
CREATE INDEX IF NOT EXISTS idx_poll_options_poll ON poll_options (poll_id);            -- ตัวเลือกของโหวต
CREATE INDEX IF NOT EXISTS idx_repayments_trip ON repayments (trip_id);                -- การคืนเงินของทริป
CREATE INDEX IF NOT EXISTS idx_user_trip_history_user ON user_trip_history (user_id);  -- ทริปล่าสุดของผู้ใช้
