-- V3: ความเคลื่อนไหวล่าสุดของทริป (เขียนโดย Observer: TripEventListener)
CREATE TABLE trip_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id    BIGINT       NOT NULL,
    member_id  BIGINT,
    event_type VARCHAR(30)  NOT NULL,
    message    VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_trip_events_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    -- สมาชิกออกจากทริปแล้ว ประวัติยังอยู่ แต่ไม่ชี้ไปหาสมาชิกคนนั้น
    CONSTRAINT fk_trip_events_member FOREIGN KEY (member_id) REFERENCES trip_members (id) ON DELETE SET NULL
);

-- ดึง "ล่าสุดของทริปนี้" บ่อย จึงทำ index ตามลำดับที่ใช้เรียง
CREATE INDEX idx_trip_events_trip_created ON trip_events (trip_id, created_at DESC);
